---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible molecule docker molecule-docker 
script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
